- name: say hello
  ansible.builtin.shell: echo "starting provisioning OR updating of docker jenkins..."
  register: say_hello_result

- name: debug say hello
  ansible.builtin.debug:
    msg: "{{ say_hello_result.stdout }}"
  ignore_errors: true