name: base-actions-jenkins-sandbox
run-name: Jenkins Sandbox
on:
  push:
    branches:
      - sandbox
  pull_request:
    branches:
      - sandbox
jobs:
  checkout-start:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4