name: base-actions-jenkins-sandbox
run-name: Jenkins Sandbox
on:
  push:
    branches:
      - sandbox
  pull_request:
    branches:
      - sandbox
jobs:
  checkout-start:
    environment: sandbox
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
  list-stats:
    environment: sandbox
    needs: checkout-start
    runs-on: self-hosted
    steps:
      - name: Make the script files executable
        run: chmod +x ci-cd-scripts/show-env.sh
      - name: Run the scripts
        run: |
          ./ci-cd-scripts/show-env.sh
  terraform:
    environment: sandbox
    defaults:
      run:
        working-directory: ./terraform/applications/jenkinssbx
    needs: [checkout-start, list-stats]
    runs-on: self-hosted
    steps:
      - name: terraform init
        run: TF_LOG=TRACE terraform init -reconfigure -var-file="env/local.tfvars"