name: base-actions-jenkins-sandbox
run-name: Jenkins Sandbox
on:
  push:
    branches:
      - sandbox
  pull_request:
    branches:
      - sandbox
jobs:
  checkout-start:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
  list-stats:
    runs-on: self-hosted
    steps:
      - name: Make the script files executable
        run: chmod +x ci-cd-scripts/show-env.sh
      - name: Run the scripts
        run: |
          ./ci-cd-scripts/show-env.sh